### ISSUE TITLE
Auto Fill-in Default Parameters

### ISSUE THREAD

**Issue by async0x42** [Thundernerd/Unity3D-ExtendedEvent#2]
It would be great if this could be supported!

For example:
`
        public void Shake(float duration, Vector2 strength, int vibrato = 10, float randomness = .1f, float initialAngle = -1f, Vector3 rotation = default(Vector3), float smoothness = .1f)
        {
`

When using this with ExtendedEvent, all parameters are empty. Ideally, this would be filled in by default.

Thanks for ExtendedEvent, works really well!

**Comment by Thundernerd** [comment]
Thanks for the suggestion.

I've added default values for both fields and method parameters (95fc490, 676daee).
The next release will contains this and will be up soon.

If you have any further questions/issues feel free to open a new issue.
