### ISSUE TITLE
InvalidCastException on reflected method

### ISSUE THREAD

**Issue by async0x42** [Thundernerd/Unity3D-ExtendedEvent#4]
It worked with the previous version, however now I  get a "Nothing Selected" dropdown when attempting to pick a method to call.

And as a note to this, if I discard the changes using GIT, Unity will display the proper method. If I deselect the object, and then reselect it, "Nothing Selected" is displayed again

`InvalidCastException: Cannot cast from source type to destination type.
ExtendedEvent+Parameter.LoadDefaultValue () (at Assets/Libraries/ExtendedEvent/ExtendedEvent.cs:200)
ExtendedEvent+Parameter..ctor (System.Reflection.ParameterInfo info) (at Assets/Libraries/ExtendedEvent/ExtendedEvent.cs:125)
ExtendedEvent+Member..ctor (System.Reflection.MethodInfo info, System.Type infoType, System.Type type, System.Reflection.ParameterInfo[] parameters) (at Assets/Libraries/ExtendedEvent/ExtendedEvent.cs:381)
ExtendedEvent+GameObjectContainer.ReadObject (System.Type type, System.Collections.Generic.List 1& tempList) (at Assets/Libraries/ExtendedEvent/ExtendedEvent.cs:720)
ExtendedEvent+GameObjectContainer.Reset () (at Assets/Libraries/ExtendedEvent/ExtendedEvent.cs:643)
ExtendedEventPropertyDrawer.DrawElementInternal (Rect rect, Int32 index, Boolean isActive, Boolean isFocused) (at Assets/Libraries/ExtendedEvent/Editor/ExtendedEventPropertyDrawer.cs:119)
UnityEditorInternal.ReorderableList.DoListElements (Rect listRect) (at C:/buildslave/unity/build/Editor/Mono/GUI/ReorderableList.cs:547)
UnityEditorInternal.ReorderableList.DoList (Rect rect) (at C:/buildslave/unity/build/Editor/Mono/GUI/ReorderableList.cs:390)
ExtendedEventPropertyDrawer.OnGUI (Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at Assets/Libraries/ExtendedEvent/Editor/ExtendedEventPropertyDrawer.cs:48)
UnityEditor.PropertyDrawer.OnGUISafe (Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at C:/buildslave/unity/build/Editor/Mono/ScriptAttributeGUI/PropertyDrawer.cs:23)
UnityEditor.PropertyHandler.OnGUI (Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, Boolean includeChildren) (at C:/buildslave/unity/build/Editor/Mono/ScriptAttributeGUI/PropertyHandler.cs:134)
UnityEditor.EditorGUI.PropertyFieldInternal (Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, Boolean includeChildren) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:4891)
UnityEditor.EditorGUI.PropertyField (Rect position, UnityEditor.SerializedProperty property, Boolean includeChildren) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorGUIBindings.gen.cs:963)
UnityEditor.EditorGUI.PropertyField (Rect position, UnityEditor.SerializedProperty property) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorGUIBindings.gen.cs:958)
UnityEditor.Editor.OptimizedInspectorGUIImplementation (Rect contentRect) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorBindings.gen.cs:234)
UnityEditor.GenericInspector.OnOptimizedInspectorGUI (Rect contentRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/GenericInspector.cs:33)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1211)
UnityEditor.InspectorWindow.DrawEditors (UnityEditor.Editor[] editors) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1028)
UnityEditor.InspectorWindow.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:352)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
UnityEditor.HostView:OnGUI()
`

**Comment by Thundernerd** [comment]
Could you give some more context on the method you are using?
What parameters does it have?

Thanks.

**Comment by async0x42** [comment]
Just Vectors and floats I think:
![image](https://cloud.githubusercontent.com/assets/3268854/12499372/1be2811a-c078-11e5-9e0a-9d80802961d2.png)

Your latest commit fixed my issues, thanks!

**Comment by Thundernerd** [comment]
Yeah I noticed it was crashing on floats as well. I think it appeared if you have a default value of 0 for floats, and null for objects etc. This way it cannot cast them to its necessary type (weird for floats though, but hey, it works now).
