### ISSUE TITLE
Argument Exception

### ISSUE THREAD

**Issue by keenanwoodall** [Thundernerd/Unity3D-ExtendedEvent#5]
Non-project-specific error

ArgumentException: Field "ExtendedEvent" defined on type "Namespace.EventContainerClass" is not a field on the target object which is of type "Namespace.ClassThatHoldsSerializedEventContainerClass".
Parameter name: obj

My error

ArgumentException: Field OnIsShown defined on type IDEAD.ObjectVisibilityEvents is not a field on the target object which is of type IDEAD.ObjectBase.
Parameter name: obj

**Comment by Thundernerd** [comment]
Apologies for the delayed reply.

You can try checking out this commit (2e1333a) and see if the problem still exists. As for the problem itself I'm not sure what's causing it, sorry.

The current version that you're using (I'm assume you're on the master branch) is a bit sloppy in the way it's written. The V3 branch is basically a complete rewrite and should be way faster and also more stable.

Edit: I forgot to include that the new version is definitely not backward compatible.
